#!/usr/bin/env python3
"""Splice the generated results table into the post.

Kept separate from the prose so the table can be regenerated as the sweep
finishes without anyone editing 500 rows by hand, and so the post always
carries the same numbers the records do.
"""

import pathlib
import subprocess
import sys

POST = pathlib.Path(
    "/home/ubuntu/code/sbomify.com/.claude/worktrees/blog-500-projects/"
    "content/posts/2026-08-10-500-open-source-projects.md"
)
TABLE = pathlib.Path("/home/ubuntu/sbomify-eval/blog_table.md")
MARKER = "<!-- TABLE -->"

subprocess.run(
    [sys.executable, "/home/ubuntu/sbomify-eval/make_blog_table.py", "--out", str(TABLE)],
    check=True,
)

body = POST.read_text()
table = TABLE.read_text().strip()

start = body.find(MARKER)
if start == -1:
    # Already injected once: replace between the generated-by comment and the
    # heading that follows, so this stays idempotent.
    start = body.find("<!-- generated by make_blog_table.py")
    if start == -1:
        sys.exit("no marker and no previous table found in the post")
    end = body.find("\n## ", start)
    if end == -1:
        sys.exit("could not find the end of the previous table")
    POST.write_text(body[:start] + table + "\n" + body[end:])
else:
    POST.write_text(body[:start] + table + body[start + len(MARKER) :])

rows = sum(1 for line in table.splitlines() if line.startswith("| ["))
print(f"injected {rows} rows into {POST.name}")

# dprint pads table columns to a common width, so a freshly generated table
# always fails `bun run lint:markdown` until it is formatted. Doing it here
# keeps regeneration a single command instead of a command and a gotcha.
fmt = subprocess.run(
    ["bun", "run", "lint:markdown:fix"],
    cwd="/home/ubuntu/code/sbomify.com/.claude/worktrees/blog-500-projects",
    capture_output=True,
    text=True,
)
print("formatted" if fmt.returncode == 0 else f"dprint failed:\n{fmt.stderr[:400]}")
